# Generated by Django 6.0.6 on 2026-06-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_alter_node_is_active'),
        ('plans', '0002_alter_plan_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='nodes',
            field=models.ManyToManyField(blank=True, to='nodes.node', verbose_name='关联节点'),
        ),
    ]
