FROM python:3.13-slim

RUN pip install uv

WORKDIR /app

COPY app/pyproject.toml app/uv.lock ./
RUN uv sync --frozen

COPY app/ .

RUN groupadd -r django && useradd -r -g django django && chown -R django:django /app
USER django

CMD ["uv", "run", "manage.py", "run_scheduler"]
