FROM node:22-alpine AS builder
WORKDIR /build

COPY web/package.json web/package-lock.json ./
RUN npm ci
COPY web/ .
RUN npm run build-only

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /build/dist /app/web/dist
