# Generated by Django 6.0.6 on 2026-06-22 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_paymentconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(verbose_name='金额(分)')),
                ('out_trade_no', models.CharField(max_length=64, unique=True, verbose_name='商户订单号')),
                ('trade_no', models.CharField(blank=True, default='', max_length=64, verbose_name='支付宝交易号')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('closed', '已关闭')], db_index=True, default='pending', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '支付订单',
                'db_table': 'payment_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
