# Generated by Django 6.0.6 on 2026-06-17 07:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='节点名称')),
                ('protocol', models.CharField(choices=[('vless', 'VLESS'), ('vmess', 'VMess'), ('shadowsocks', 'Shadowsocks'), ('trojan', 'Trojan'), ('hysteria2', 'Hysteria2')], max_length=32, verbose_name='协议')),
                ('address', models.CharField(max_length=256, verbose_name='地址')),
                ('port', models.IntegerField(verbose_name='端口')),
                ('config', models.JSONField(blank=True, default=dict, help_text='各协议的专属配置，如 flow/encryption/obfs 等', verbose_name='协议配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '节点',
                'db_table': 'nodes',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '订阅',
                'db_table': 'subscriptions',
            },
        ),
    ]
