# Generated by Django 6.0.6 on 2026-06-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0007_alter_node_config_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="deployed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最后部署时间"
            ),
        ),
    ]
