# Generated by Django 6.0.6 on 2026-06-22 08:32

from django.db import migrations

import config.fields


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0008_node_deployed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="ssh_password",
            field=config.fields.EncryptedCharField(
                blank=True,
                help_text="密码认证，与私钥二选一（自动加密存储）",
                max_length=1024,
                verbose_name="SSH 密码",
            ),
        ),
    ]
